version: '2'
services:
    mongodb:
        image: mongo
        volumes:
            - ./mongodb:/data/db
        ports:
            - '27017:27017'

    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
        command: >
            --requirepass REDIS_PASSWORD --appendonly yes
