FROM node:10.15.0-alpine

RUN npm install -g apollo

WORKDIR /app
RUN apk update && apk add --virtual build-dependencies build-base gcc wget bash python
ADD package.json tsconfig.json tslint.json /app/
RUN yarn
ADD .env .env.example /app/

CMD ["yarn", "dev_docker"]