// Generated by https://quicktype.io

export interface NewPaymentTransaction {
    partnerCode: string;
    orderId: string;
    requestId: string;
    amount: number;
    responseTime: number;
    message: string;
    resultCode: number;
    payUrl: string;
}
